exports.handler = async (event) => {
    const allowedEmails = [
        'ardaakkiz@gmail.com',
        'baran.ozer.yuce@gmail.com',
        'hello@asinbaba.com',
        'emrekoca86@gmail.com',
        "gulistanagcal@hotmail.com",
        "emrahkeles0604@gmail.com",
        "kahyeogluf@gmail.com",
        "emrealtan1525@gmail.com",
        "serdar_tur@hotmail.com",
        "ademoglu.h@gmail.com",
        "gezgin48@gmail.com",
        "volkan.eeris@gmail.com",
        "burakamazonco@gmail.com", // manuel eklendi
        "tugbacobanoglu_2@hotmail.com",
        "fatihkansudemircan@gmail.com",
        "gamze.cobannn@gmail.com",
        "nurcanpeksen7380@gmail.com",
        "kerempeksen7380@gmail.com",
        "mehmetozturk1903@outlook.com.tr",
        "okilavuz78@gmail.com",
        "elifa@degainternational.net",
        "tfscerci@gmail.com",
        "niyazi_kabak@hotmail.com",
        "geneburak@gmail.com",
        "merveesahin96@gmail.com",
        "sinan.sumaktas@outlook.com",
        "Hachikokuki@gmail.com",
        "gulcihanozyuksel@gmail.com",
        "samet501@windowslive.com",
        "kanguxx@gmail.com",
        "ufukposluk@hotmail.com",
        "burakamazonco@gmail.com",
        "ademkizilkaya87@gmail.com",
        "onrergul@gmail.com",
        "omerfaruk567248@gmail.com",
        "omeryardim2@hotmail.com",
        "Alexideaa@gmail.com",
        "memetsaid619@gmail.com",
        "sefagler@gmail.com",
        "cigdemozaltin@gmail.com",
        "asrinstoreseller@gmail.com",
        "enesatak19072002@gmail.com",
        "efecantfamazon@gmail.com",
        "ismetbukuamazon@gmail.com",
        "llcdarkblue@gmail.com",
        "aidakimuk@gmail.com",
        "canberkkundakci@hotmail.com",
        "erdincze@hotmail.com",
        "burakozen95@gmail.com",
        "ayazgonca@gmail.com",
        "mesutsaglam55@hotmail.com",
        "gamze.cobannn@gmail.com",
        "ykurtyemez@gmail.com",
        "simsekgulsumdogan@gmail.com",
        "bulent.altiparmakk@gmail.com",
        "bilalkbk94@gmail.com",
        "mucahitarslan679@gmail.com",
        "burakozen95@gmail.com",
        "vedatlevent52@gmail.com",
        "emrahbolat3455@gmail.com",
        "ferhatyzlm@gmail.com",
        "nevruzdalkilic@gmail.com",
        "ylz.dincer@gmail.com",
        "eminetanrikuluaydin@gmail.com",
        "emre.tsdln@gmail.com",
        "barsugr1@gmail.com",
        "ibrahimbabahan8@gmail.com",
        "tugbacobanoglu_2@hotmail.com",
        "ekremhndolu@gmail.com",
        "adastore.tr@gmail.com",
        "bertugberber@gmail.com",
        "eyetisen1144@gmail.com",
        "aarsak@gmail.com",
        "tahiraksoy.mkm@gmail.com",
        "erkaysahin057@gmail.com",
        "farukerguncu6@hotmail.com",
        "babilteknoloji@gmail.com",
        "batu.sonal39@gmail.com",
        "serrabolluk@gmail.com",
        "damla.ayar0717@gmail.com",
        "baharsenay@gmail.com",
        "selin_karakas@yahoo.com",
        "nurbuyukoztekin@gmail.com",
        "euzek4680@gmail.com",
        "didemyurga@gmail.com",
        "dilekgundoganalici@gmail.com",
        "icerikhizmeti@gmail.com",
        "murattekin.marketing@gmail.com",
        "fundacimen8744@gmail.com",
        "drmervesari@yahoo.com",
        "ar7ogredik@gmail.com",
        "habiperdm@gmail.com"
    ]
    const userEmail = event.queryStringParameters.email;

    const isAllowed = allowedEmails.includes(userEmail);
    
    return {
        statusCode: 200,
        body: JSON.stringify({ allowed: isAllowed }),
    };
};